---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:v0.7.1
  commands:
  - shellcheck scripts/* githooks/*
- name: shfmt
  image: mvdan/shfmt:v3.2.2-alpine
  commands:
  - shfmt -d .
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
    - sh scripts/durl.sh
- name: golangci-lint
  image: golangci/golangci-lint:v1.39.0-alpine
  commands:
  - golangci-lint run
  volumes: &volumes
  - name: gopath
    path: /go
- name: test
  image: golang:1.16.3
  commands:
  # bash and cgo seem to be required
  - bash ci/test.sh
  environment:
    CC_TEST_REPORTER_ID:
      from_secret: cc_test_reporter_id
  volumes: *volumes
