---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:v0.7.1
  commands:
  - shellcheck scripts/* githooks/*
- name: shfmt
  image: mvdan/shfmt:v3.1.1-alpine
  commands:
  - shfmt -d .
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
    - sh scripts/durl.sh
- name: golangci-lint
  image: golangci/golangci-lint:v1.27.0-alpine
  commands:
  - golangci-lint run
  volumes: &volumes
  - name: gopath
    path: /go
- name: codecov
  image: golang:1.14.2
  commands:
  # bash and cgo seem to be required
  - go test -race -coverprofile=coverage.out -covermode=atomic ./timeout
  - curl -s https://codecov.io/bash > /tmp/codecov.sh
  - test "$LOCAL" = "true" -o "$DRONE_BUILD_EVENT" = "pull_request" || bash /tmp/codecov.sh
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token
  volumes: *volumes
